### ISSUE TITLE
Evaluation details on SVAMP

### ISSUE THREAD

**Issue by jinghan23** [GAIR-NLP/abel#14]
Hi @EthanC111 , I'm looking up for recently published math models and so glad to see your brilliant work! 

In order to gain a deeper understanding and potentially build upon your results, I kindly request some additional information when evaluating on SVAMP benchmark.

Here are my specific questions:
* Shot number in the few-shot setting: Can you clarify whether the shot number for SVAMP follows the 5-shot approach found in MAmmoTH or the 4-shot method utilized in OpenCompass?
* Prompts used during evaluation: Would you be able to share the exact prompts employed when evaluating models (like Mistral, LLaMA,. etc.) on SVAMP? 
* Additional evaluation details: Are there any other crucial aspects of the evaluation process that I should take into account when working with SVAMP?

Presently, I can only locate a shell script evaluating in zero-shot setting on GSM8k, MATH, etc.,  within the 'evaluation' directory. Many thanks in advance for your assistance and guidance!

**Comment by lixuefeng02** [comment]
你好！
1 我们没有参考MAmmoTH或者Opencompass的few-shot实现，而是自己选取了SVAMP中的**5**个样本作为few-shot的例子;
2 
```

Instruction = '''You are an expect in mathematical reasoning. Here you are asked to answer one mathematical question starting with 'Question:'. Your answer will start with 'Answer: let's think step by step'. 

The answer needs to include necessary reasoning steps to demonstrate your thinking procedure, and the final result of your calculation is demonstrated at the end of your answer starting with '[ANSWERKEY]'. 

Here are some examples starting with 'Question: ' for your reference.
'''

svamp_examples='''Question: 
There are 87 oranges and 290 bananas in Philip's collection. If the bananas are organized into 2 groups and oranges are organized into 93 groupsHow big is each group of bananas?
Answer: 
Let's think step by step.
( 290.0 / 2.0 ) = 145.0\n[ANSWERKEY] 145.0

Question: 
Marco and his dad went strawberry picking. Marco's dad's strawberries weighed 11 pounds. If together their strawberries weighed 30 pounds.How much did Marco's strawberries weigh?
Answer: 
Let's think step by step.
( 30.0 - 11.0 ) = 19.0\n[ANSWERKEY] 19.0

Question: 
Edward spent $ 6 to buy 2 books each book costing him the same amount of money. Now he has $ 12.How much did each book cost?
Answer: 
Let's think step by step.
( 6.0 / 2.0 ) = 3.0\n[ANSWERKEY] 3.0

Question: 
Frank was reading through his favorite book. The book had 3 chapters, each with the same number of pages. It has a total of 594 pages. It took Frank 607 days to finish the book.How many pages are in each chapter?
Answer: 
Let's think step by step.
( 594.0 / 3.0 ) = 198.0\n[ANSWERKEY] 198.0

Question: 
There were 78 dollars in Olivia's wallet. She spent 15 dollars at a supermarket.How much money does she have left?
Answer: 
Let's think step by step.
( 78.0 - 15.0 ) = 63.0\n[ANSWERKEY] 63.0

'''

svamp_template: str = Instruction + svamp_examples + "Question:\n[INPUT]\nAnswer:\nLet's think step by step.\n"
```
对于基座模型，[ANSWERKEY]都会被替换为"####".

3 从其他benchmark的评测结果，我们发现few-shot中例子的解答的详细程度对于性能有很大影响，对于SVAMP应该也是如此。

**Comment by lixuefeng02** [comment]
对于第三点，我们目前仓库中的评估脚本会把模型输出95但是答案是95.0的情况判错，所以可能要对评估脚本进行一些修正.
